newVariables = {

"Event.Number": "Event_number",
"Event.ReadTime": "Event_readtime",
"Event.ProcTime": "Event_proctime",

#"LHCOEvent.Event": "LHCOEvent_event",
#"LHCOEvent.Trigger": "LHCOEvent.Trigger",

#"LHEFEvent.Event": "LHEFEvent_event",
#"LHEFEvent.ProcessID": "LHEFEvent_processid",
#"LHEFEvent.Weight": "LHEFEvent_weight",
#"LHEFEvent.ScalePDF": "LHEFEvent_scalepdf",
#"LHEFEvent.AlphaQED": "LHEFEvent_alphaqed",
#"LHEFEvent.AlphaQCD": "LHEFEvent_alphaqcd",

#"LHEFWeight.ID": "LHEFWeight_id",
#"LHEFWeight.weight": "LHEFWeight_weight",

#"HepMCEvent.Event": "HepMCEvent_event",
#"HepMCEvent.ProcessID": "HepMCEvent_processid",
#"HepMCEvent.MPI": "HepMCEvent_mpi",
#"HepMCEvent.Weight": "HepMCEvent_weight",
#"HepMCEvent.Scale": "HepMCEvent_scale",
#"HepMCEvent.AlphaQED": "HepMCEvent_alphaqed",
#"HepMCEvent.AlphaQCD": "HepMCEvent_aphaqcd",
#"HepMCEvent.ID1": "HepMCEvent_id1",
#"HepMCEvent.ID2": "HepMCEvent_id2",
#"HepMCEvent.X1": "HepMCEvent_x1",
#"HepMCEvent.X2": "HepMCEvent_x2",
#"HepMCEvent.ScalePDF": "HepMCEvent_scalepdf",
#"HepMCEvent.PDF1": "HepMCEvent_pdf1",
#"HepMCEvent.PDF2": "HepMCEvent_pdf2",

"MissingET.MET": "MissingET_met",
"MissingET.Eta": "MissingET_eta",
"MissingET.Phi": "MissingET_phi",

"PhotonTight.PT": "PhotonTight_pt",
"PhotonTight.Eta": "PhotonTight_eta",
"PhotonTight.Phi": "PhotonTight_phi",
#"PhotonTight.E": "PhotonTight_e",
"PhotonTight.T": "PhotonTight_t",
"PhotonTight.EhadOverEem": "PhotonTight_ehadovereem",
#"PhotonTight.Particles": "PhotonTight_particles",
"PhotonTight.IsolationVar": "PhotonTight_isolationvar",
"PhotonTight.IsolationVarRhoCorr": "PhotonTight_isolationvarrhocorr",
"PhotonTight.SumPtCharged": "PhotonTight_sumptcharged",
"PhotonTight.SumPtNeutral": "PhotonTight_sumptneutral",
"PhotonTight.SumPtChargedPU": "PhotonTight_sumptchargedpu",
"PhotonTight.SumPt": "PhotonTight_sumpt",

"MuonTight.PT": "MuonTight_pt",
"MuonTight.Eta": "MuonTight_eta",
"MuonTight.Phi": "MuonTight_phi",
"MuonTight.T": "MuonTight_t",
"MuonTight.Charge": "MuonTight_charge",
#"MuonTight.Particle": "MuonTIght_particle",
"MuonTight.IsolationVar": "MuonTight_isolationvar",
"MuonTight.IsolationVarRhoCorr": "MuonTight_isolationvarrhocorr",
"MuonTight.SumPtCharged": "MuonTight_sumptcharged",
"MuonTight.SumPtNeutral": "MuonTight_sumptneutral",
"MuonTight.SumPtChargedPU": "MuonTight_sumptchargedpu",
"MuonTight.SumPt": "MuonTight_sumpt",

"Jet.PT": "Jet_pt",
"Jet.Eta": "Jet_eta",
"Jet.Phi": "Jet_phi",
"Jet.Mass": "Jet_mass",

"Electron.PT": "Electron_pt",
"Electron.Eta": "Electron_eta",
"Electron.Phi": "Electron_phi",
"Electron.T": "Electron_t",
"Electron.Charge": "Electron_charge",
"Electron.EhadOverEem": "Electron_ehadovereem",
"Electron.IsolationVar": "Electron_isolationvar",
"Electron.IsolationVarRhoCorr": "Electron_isolationvarrhocorr",
"Electron.SumPtCharged": "Electron_sumptcharged",
"Electron.SumPtNeutral": "Electron_sumptneutral",
"Electron.SumPtChargedPU": "Electron_sumptchargedpu",
"Electron.SumPt": "Electron_sumpt",

}
